version = 0.1

[default.deploy.parameters]
stack_name = "erglytics-dev"
resolve_s3 = true
s3_prefix = "erglytics-dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "CognitoDomainPrefix=\"rowlytics-auth-recovery-20260314\" AppBaseUrl=\"https://xft207g10i.execute-api.us-east-2.amazonaws.com/Prod\" SesFromEmail=\"updates@erglytics.com\" UsersTableName=\"RowlyticsUsers\" TeamsTableName=\"RowlyticsTeams\" TeamMembersTableName=\"RowlyticsTeamMembers\" RecordingsTableName=\"RowlyticsRecordings\" WorkoutsTableName=\"RowlyticsWorkouts\" UploadBucketName=\"rowlyticsuploads\" UserPoolName=\"RowlyticsUserPool\" UserPoolClientName=\"RowlyticsUserPoolClient\" ManageSharedResources=\"false\" ExistingUserPoolId=\"us-east-2_jXENfSnPZ\" ExistingUserPoolClientId=\"2lu6fopujo3usd6qdt47nt3b20\""

[default.global.parameters]
region = "us-east-2"
