AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Rowlytics backend resources (DynamoDB tables)

Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RowlyticsUsers
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH

  TeamsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RowlyticsTeams
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: teamId
          AttributeType: S
      KeySchema:
        - AttributeName: teamId
          KeyType: HASH

  TeamMembersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RowlyticsTeamMembers
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: teamId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: teamId
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE

  RecordingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RowlyticsRecordings
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: recordingId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: recordingId
          KeyType: RANGE

  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: rowlyticsuploads
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
              - PUT
              - HEAD
            AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
            MaxAge: 300

Outputs:
  UsersTableName:
    Value: !Ref UsersTable
  TeamsTableName:
    Value: !Ref TeamsTable
  TeamMembersTableName:
    Value: !Ref TeamMembersTable
  RecordingsTableName:
    Value: !Ref RecordingsTable
  UploadBucketName:
    Value: !Ref UploadBucket
