AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Rowlytics backend resources (DynamoDB tables + Cognito + S3)

Parameters:
  CognitoDomainPrefix:
    Type: String
    AllowedPattern: "^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$"
    ConstraintDescription: "Must be 1-63 chars of lowercase letters, numbers, or hyphens."
    Description: Globally unique prefix for the Cognito hosted UI domain.

  AppBaseUrl:
    Type: String
    Default: https://v353vlxck0.execute-api.us-east-2.amazonaws.com/Prod
    Description: Base URL used for Cognito callback and logout redirects.

  SesFromEmail:
    Type: String
    Description: Verified SES sender email (our team email). Must be verified in SES for this region/account.

  UsersTableName:
    Type: String
    Default: RowlyticsUsers
    Description: DynamoDB table name for user profiles.

  TeamsTableName:
    Type: String
    Default: RowlyticsTeams
    Description: DynamoDB table name for teams.

  TeamMembersTableName:
    Type: String
    Default: RowlyticsTeamMembers
    Description: DynamoDB table name for team memberships.

  RecordingsTableName:
    Type: String
    Default: RowlyticsRecordings
    Description: DynamoDB table name for recordings.

  WorkoutsTableName:
    Type: String
    Default: RowlyticsWorkouts
    Description: DynamoDB table name for workouts.

  UploadBucketName:
    Type: String
    Default: rowlyticsuploads
    Description: S3 bucket name for uploaded recordings. Must be globally unique.

  UserPoolName:
    Type: String
    Default: RowlyticsUserPool
    Description: Cognito User Pool display name.

  UserPoolClientName:
    Type: String
    Default: RowlyticsUserPoolClient
    Description: Cognito User Pool client display name.

  ManageSharedResources:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: Set to false to reuse existing DynamoDB/S3/Cognito resources instead of creating them in this stack.

  ExistingUserPoolId:
    Type: String
    Default: ""
    Description: Required when ManageSharedResources=false. Existing Cognito User Pool ID to use.

  ExistingUserPoolClientId:
    Type: String
    Default: ""
    Description: Required when ManageSharedResources=false. Existing Cognito User Pool Client ID to use.

Conditions:
  CreateManagedResources: !Equals [!Ref ManageSharedResources, "true"]

Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Condition: CreateManagedResources
    Properties:
      TableName: !Ref UsersTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  TeamsTable:
    Type: AWS::DynamoDB::Table
    Condition: CreateManagedResources
    Properties:
      TableName: !Ref TeamsTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: teamId
          AttributeType: S
        - AttributeName: teamName
          AttributeType: S
      KeySchema:
        - AttributeName: teamId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: TeamNameIndex
          KeySchema:
            - AttributeName: teamName
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  TeamMembersTable:
    Type: AWS::DynamoDB::Table
    Condition: CreateManagedResources
    Properties:
      TableName: !Ref TeamMembersTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: teamId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: teamId
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: UserIdIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: teamId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  RecordingsTable:
    Type: AWS::DynamoDB::Table
    Condition: CreateManagedResources
    Properties:
      TableName: !Ref RecordingsTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: recordingId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: recordingId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: UserCreatedAtIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  WorkoutsTable:
    Type: AWS::DynamoDB::Table
    Condition: CreateManagedResources
    Properties:
      TableName: !Ref WorkoutsTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: workoutId
          AttributeType: S
        - AttributeName: completedAt
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: workoutId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: UserCompletedAtIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: completedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  UploadBucket:
    Type: AWS::S3::Bucket
    Condition: CreateManagedResources
    Properties:
      BucketName: !Ref UploadBucketName
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
              - PUT
              - HEAD
            AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
            MaxAge: 300

  UserPool:
    Type: AWS::Cognito::UserPool
    Condition: CreateManagedResources
    Properties:
      UserPoolName: !Ref UserPoolName
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Condition: CreateManagedResources
    Properties:
      ClientName: !Ref UserPoolClientName
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
        - aws.cognito.signin.user.admin
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - !Sub "${AppBaseUrl}/auth/callback"
      LogoutURLs:
        - !Sub "${AppBaseUrl}/signin"
      SupportedIdentityProviders:
        - COGNITO

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Condition: CreateManagedResources
    Properties:
      Domain: !Ref CognitoDomainPrefix
      UserPoolId: !Ref UserPool

  RowlyticsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      BinaryMediaTypes:
        - image/png
        - image/jpeg
        - image/jpg
        - image/gif
        - image/webp
        - image/svg+xml
        - application/octet-stream
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  RowlyticsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Handler: app.lambda_handler
      Runtime: python3.11
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          ROWLYTICS_ENV: production
          ROWLYTICS_AUTH_REQUIRED: "true"
          ROWLYTICS_USERS_TABLE: !Ref UsersTableName
          ROWLYTICS_TEAMS_TABLE: !Ref TeamsTableName
          ROWLYTICS_TEAM_MEMBERS_TABLE: !Ref TeamMembersTableName
          ROWLYTICS_TEAM_MEMBERS_USER_INDEX: UserIdIndex
          ROWLYTICS_TEAMS_NAME_INDEX: TeamNameIndex
          ROWLYTICS_RECORDINGS_TABLE: !Ref RecordingsTableName
          ROWLYTICS_RECORDINGS_CREATED_AT_INDEX: UserCreatedAtIndex
          ROWLYTICS_WORKOUTS_TABLE: !Ref WorkoutsTableName
          ROWLYTICS_WORKOUTS_COMPLETED_AT_INDEX: UserCompletedAtIndex
          ROWLYTICS_MAX_PAGE_SIZE: "50"
          ROWLYTICS_TEAM_MEMBERS_PAGE_SIZE: "20"
          ROWLYTICS_RECORDINGS_PAGE_SIZE: "8"
          ROWLYTICS_WORKOUTS_PAGE_SIZE: "8"
          ROWLYTICS_UPLOAD_BUCKET: !Ref UploadBucketName
          ROWLYTICS_COGNITO_DOMAIN: !Sub "${CognitoDomainPrefix}.auth.${AWS::Region}.amazoncognito.com"
          ROWLYTICS_COGNITO_CLIENT_ID: !If [CreateManagedResources, !Ref UserPoolClient, !Ref ExistingUserPoolClientId]
          ROWLYTICS_COGNITO_REDIRECT_URI: !Sub "${AppBaseUrl}/auth/callback"
          ROWLYTICS_COGNITO_LOGOUT_REDIRECT_URI: !Sub "${AppBaseUrl}/signin"
          ROWLYTICS_COGNITO_USER_POOL_ID: !If [CreateManagedResources, !Ref UserPool, !Ref ExistingUserPoolId]
          SES_FROM_EMAIL: !Ref SesFromEmail
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTableName
        - DynamoDBCrudPolicy:
            TableName: !Ref TeamsTableName
        - DynamoDBCrudPolicy:
            TableName: !Ref TeamMembersTableName
        - DynamoDBCrudPolicy:
            TableName: !Ref RecordingsTableName
        - DynamoDBCrudPolicy:
            TableName: !Ref WorkoutsTableName
        - S3CrudPolicy:
            BucketName: !Ref UploadBucketName
        - Statement:
            - Effect: Allow
              Action:
                - cognito-idp:DeleteUser
                - cognito-idp:AdminDeleteUser
              Resource: !If
                - CreateManagedResources
                - !GetAtt UserPool.Arn
                - !Sub "arn:${AWS::Partition}:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${ExistingUserPoolId}"
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: "*"
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref RowlyticsApi
            Path: /
            Method: ANY

        SignIn:
          Type: Api
          Properties:
            RestApiId: !Ref RowlyticsApi
            Path: /signin
            Method: ANY
        AuthCallback:
          Type: Api
          Properties:
            RestApiId: !Ref RowlyticsApi
            Path: /auth/callback
            Method: ANY
        Logout:
          Type: Api
          Properties:
            RestApiId: !Ref RowlyticsApi
            Path: /logout
            Method: ANY
        ProxyApi:
          Type: Api
          Properties:
            RestApiId: !Ref RowlyticsApi
            Path: /{proxy+}
            Method: ANY

Outputs:
  UsersTableName:
    Value: !Ref UsersTableName
  TeamsTableName:
    Value: !Ref TeamsTableName
  TeamMembersTableName:
    Value: !Ref TeamMembersTableName
  RecordingsTableName:
    Value: !Ref RecordingsTableName
  WorkoutsTableName:
    Value: !Ref WorkoutsTableName
  UploadBucketName:
    Value: !Ref UploadBucketName
  UserPoolId:
    Value: !If [CreateManagedResources, !Ref UserPool, !Ref ExistingUserPoolId]
  UserPoolClientId:
    Value: !If [CreateManagedResources, !Ref UserPoolClient, !Ref ExistingUserPoolClientId]
  UserPoolDomain:
    Value: !Sub "${CognitoDomainPrefix}.auth.${AWS::Region}.amazoncognito.com"
  RowlyticsApiUrl:
    Value: !Sub "https://${RowlyticsApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
