AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Rowlytics backend resources (DynamoDB tables + Cognito + S3)

Parameters:
  CognitoDomainPrefix:
    Type: String
    Default: rowlytics-auth
    Description: Unique prefix for the Cognito hosted UI domain.

  AppBaseUrl:
    Type: String
    Default: https://v353vlxck0.execute-api.us-east-2.amazonaws.com/Prod
    Description: Base URL for Cognito redirect and logout URLs.

  SesFromEmail:
    Type: String
    Description: Verified SES sender email (our team email). Must be verified in SES for this region/account.

Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RowlyticsUsers
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  TeamsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RowlyticsTeams
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: teamId
          AttributeType: S
        - AttributeName: teamName
          AttributeType: S
      KeySchema:
        - AttributeName: teamId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: TeamNameIndex
          KeySchema:
            - AttributeName: teamName
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  TeamMembersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RowlyticsTeamMembers
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: teamId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: teamId
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: UserIdIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: teamId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  RecordingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RowlyticsRecordings
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: recordingId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: recordingId
          KeyType: RANGE

  WorkoutsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RowlyticsWorkouts
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: workoutId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: workoutId
          KeyType: RANGE

  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: rowlyticsuploads
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
              - PUT
              - HEAD
            AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
            MaxAge: 300

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: RowlyticsUserPool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: RowlyticsUserPoolClient
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
        - aws.cognito.signin.user.admin
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - !Sub "${AppBaseUrl}/auth/callback"
      LogoutURLs:
        - !Sub "${AppBaseUrl}/signin"
      SupportedIdentityProviders:
        - COGNITO

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref CognitoDomainPrefix
      UserPoolId: !Ref UserPool

  RowlyticsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      BinaryMediaTypes:
        - image/png
        - image/jpeg
        - image/jpg
        - image/gif
        - image/webp
        - image/svg+xml
        - application/octet-stream
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  RowlyticsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Handler: app.lambda_handler
      Runtime: python3.11
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          ROWLYTICS_ENV: production
          ROWLYTICS_AUTH_REQUIRED: "true"
          ROWLYTICS_USERS_TABLE: !Ref UsersTable
          ROWLYTICS_TEAMS_TABLE: !Ref TeamsTable
          ROWLYTICS_TEAM_MEMBERS_TABLE: !Ref TeamMembersTable
          ROWLYTICS_TEAM_MEMBERS_USER_INDEX: UserIdIndex
          ROWLYTICS_TEAMS_NAME_INDEX: TeamNameIndex
          ROWLYTICS_RECORDINGS_TABLE: !Ref RecordingsTable
          ROWLYTICS_WORKOUTS_TABLE: !Ref WorkoutsTable
          ROWLYTICS_UPLOAD_BUCKET: !Ref UploadBucket
          ROWLYTICS_COGNITO_DOMAIN: !Sub "${CognitoDomainPrefix}.auth.${AWS::Region}.amazoncognito.com"
          ROWLYTICS_COGNITO_CLIENT_ID: !Ref UserPoolClient
          ROWLYTICS_COGNITO_REDIRECT_URI: !Sub "${AppBaseUrl}/auth/callback"
          ROWLYTICS_COGNITO_LOGOUT_REDIRECT_URI: !Sub "${AppBaseUrl}/signin"
          ROWLYTICS_COGNITO_USER_POOL_ID: !Ref UserPool
          SES_FROM_EMAIL: !Ref SesFromEmail
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TeamsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TeamMembersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref RecordingsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref WorkoutsTable
        - S3CrudPolicy:
            BucketName: !Ref UploadBucket
        - Statement:
            - Effect: Allow
              Action:
                - cognito-idp:DeleteUser
                - cognito-idp:AdminDeleteUser
              Resource: !GetAtt UserPool.Arn
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: "*"
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref RowlyticsApi
            Path: /
            Method: ANY

        SignIn:
          Type: Api
          Properties:
            RestApiId: !Ref RowlyticsApi
            Path: /signin
            Method: ANY
        AuthCallback:
          Type: Api
          Properties:
            RestApiId: !Ref RowlyticsApi
            Path: /auth/callback
            Method: ANY
        Logout:
          Type: Api
          Properties:
            RestApiId: !Ref RowlyticsApi
            Path: /logout
            Method: ANY
        ProxyApi:
          Type: Api
          Properties:
            RestApiId: !Ref RowlyticsApi
            Path: /{proxy+}
            Method: ANY

Outputs:
  UsersTableName:
    Value: !Ref UsersTable
  TeamsTableName:
    Value: !Ref TeamsTable
  TeamMembersTableName:
    Value: !Ref TeamMembersTable
  RecordingsTableName:
    Value: !Ref RecordingsTable
  WorkoutsTableName:
    Value: !Ref WorkoutsTable
  UploadBucketName:
    Value: !Ref UploadBucket
  UserPoolId:
    Value: !Ref UserPool
  UserPoolClientId:
    Value: !Ref UserPoolClient
  UserPoolDomain:
    Value: !Ref UserPoolDomain
  RowlyticsApiUrl:
    Value: !Sub "https://${RowlyticsApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
