AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Rowlytics backend resources (DynamoDB tables + Cognito + S3)

Parameters:
  CognitoDomainPrefix:
    Type: String
    Default: rowlytics-auth
    Description: Unique prefix for the Cognito hosted UI domain.

Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RowlyticsUsers
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  TeamsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RowlyticsTeams
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: teamId
          AttributeType: S
        - AttributeName: teamName
          AttributeType: S
      KeySchema:
        - AttributeName: teamId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: TeamNameIndex
          KeySchema:
            - AttributeName: teamName
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  TeamMembersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RowlyticsTeamMembers
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: teamId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: teamId
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: UserIdIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: teamId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  RecordingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RowlyticsRecordings
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: recordingId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: recordingId
          KeyType: RANGE

  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: rowlyticsuploads
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
              - PUT
              - HEAD
            AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
            MaxAge: 300

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: RowlyticsUserPool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: RowlyticsUserPoolClient
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
        - aws.cognito.signin.user.admin
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - http://localhost:5000/auth/callback
      LogoutURLs:
        - http://localhost:5000/signin
      SupportedIdentityProviders:
        - COGNITO

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref CognitoDomainPrefix
      UserPoolId: !Ref UserPool

Outputs:
  UsersTableName:
    Value: !Ref UsersTable
  TeamsTableName:
    Value: !Ref TeamsTable
  TeamMembersTableName:
    Value: !Ref TeamMembersTable
  RecordingsTableName:
    Value: !Ref RecordingsTable
  UploadBucketName:
    Value: !Ref UploadBucket
  UserPoolId:
    Value: !Ref UserPool
  UserPoolClientId:
    Value: !Ref UserPoolClient
  UserPoolDomain:
    Value: !Ref UserPoolDomain
